---
- hosts: all
  become: yes

  handlers:
  - name: restart apache
    service:
      name: httpd
      state: restarted
  - name: print password
    vars:
      dsu_password_file: /tmp/dsu_password
    command: "cat {{ dsu_password_file | quote }}"
    register: output

  tasks:
    - import_tasks: postgres.yaml
    - import_tasks: ncp.yaml

    # TODO: leave selinux in enforcing mode add required rules
    - name: main | set selinux to permissive
      selinux:
        policy: targeted
        state: permissive
