---
- hosts: all
  become: yes
  tasks:
    - import_tasks: postgres.yaml
    - import_tasks: ncp.yaml
    - import_tasks: web_server.yaml

    # TODO: leave selinux in inforcing mode add required rules
    - name: main | set selinux to permissive
      selinux:
        policy: targeted
        state: permissive
