---
- hosts: all
  become: yes

  handlers:
  - name: restart apache
    service:
      name: httpd
      state: restarted
  - name: restart postgres
    service:
      name: postgresql-10
      state: restarted

  tasks:
    - import_tasks: postgres.yaml
    - import_tasks: ncp.yaml

    # TODO: leave selinux in enforcing mode add required rules
    - name: main | set selinux to permissive
      selinux:
        policy: targeted
        state: permissive
