---
- name: ncp | Add repository
  yum:
    name: https://centos7.iuscommunity.org/ius-release.rpm
    state: present

- name: ncp | ensure a list of packages installed
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - python36u
    - python36u-pip
    - python36u-mod_wsgi
    - git

- name: ncp | clone repo
  git:
    # repo: ssh://cspiess24@bitbucket.org/ncp.git
    repo: https://cspiess24@bitbucket.org/cspiess24/ncp.git
    dest: /opt/ncp
    accept_hostkey: yes
  when: enabled | default(false)

- name: ncp | install ncp requirements
  pip:
    requirements: /opt/ncp/requirements.txt
    virtualenv: /opt/ncp/ncp/venv
    virtualenv_command: /usr/bin/python3.6 -m venv

- name: ncp | copy configuration template
  template:
    src: ../templates/configuration.py.j2
    dest: /opt/ncp/ncp/ncp/configuration.py
    owner: bin
    group: wheel
    mode: 0644

