---
- name: postgresql | Add yum repository
  yum:
    name: https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-centos10-10-2.noarch.rpm
    state: present

- name: postgresql | ensure a list of packages installed
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - postgresql10
    - postgresql10-libs
    - postgresql10-server
    - python-psycopg2

- name: postgresql | check if data directory exists
  stat:
    path: /var/lib/pgsql/10/data/pg_hba.conf
  register: data_directory

- name: postgresql | run initdb
  command: /usr/pgsql-10/bin/postgresql-10-setup initdb
  register: initdb
  when: not data_directory.stat.exists

- name: postgresql | update pg_hba.conf
  copy:
    src: ../files/pg_hba.conf
    dest: /var/lib/pgsql/10/data/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0600
    backup: yes
  notify:
    - restart postgres

- name: postgresql | start service and enable at boot
  service:
    name: postgresql-10
    state: started
    enabled: yes

- name: postgresql | create database
  postgresql_db:
    name: ncp
  become_user: postgres

- name: postgresql | create user
  postgresql_user:
    db: ncp
    name: django
    password: "{{ lookup('password', '/tmp/psql_password chars=ascii_letters,digits,hexdigits,punctuation') }}"
  become_user: postgres

- name: postgresql | grant all on database
  postgresql_privs:
    db: ncp
    privs: ALL
    type: database
    role: django
  become_user: postgres
