# TODO: resolve http already installed conflict
- name: web_server | ensure a list of packages installed
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - httpd24u
    - httpd24u-mod_ssl

- name: web_server | copy django http config
  copy:
    src: ../files/django.conf
    dest: /etc/httpd/conf.d/django.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: web_server | start service and enable at boot
  service:
    name: httpd
    state: started
    enabled: yes
